# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy that I have learned in my Data Science Bootcamp. These exercises are based off fake data only!

The different tasks will be detailed by comments or text.

For my own assistance - for more resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[2, 6],
       [6, 1],
       [3, 8],
       [3, 4],
       [5, 8],
       [1, 6],
       [9, 5]], dtype=int32)

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.56960532, 0.18938309, 0.77281432, 0.19045947, 0.70419075],
       [0.23206256, 0.60002855, 0.77976668, 0.7229752 , 0.8752245 ],
       [0.60551155, 0.36485019, 0.81181106, 0.14289652, 0.09350404]])

In [17]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [18]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [19]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [20]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [21]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [27]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [28]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [29]:
# Subtract the new array of ones from the other most recent array
a4 - ones

array([[8., 0., 8., 2., 6.],
       [5., 7., 6., 3., 0.],
       [3., 6., 8., 7., 7.]])

In [30]:
# Multiply the ones array with the latest array
a4 * ones

array([[9., 1., 9., 3., 7.],
       [6., 8., 7., 4., 1.],
       [4., 7., 9., 8., 8.]])

In [31]:
# Take the latest array to the power of 2 using '**'
a4 ** 2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]], dtype=int32)

In [32]:
# Do the same thing with np.square()
np.square(a4)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]], dtype=int32)

In [33]:
# Find the mean of the latest array using np.mean()
np.mean(a4)

np.float64(6.066666666666666)

In [34]:
# Find the maximum of the latest array using np.max()
np.max(a4)

np.int32(9)

In [35]:
# Find the minimum of the latest array using np.min()
np.min(a4)

np.int32(1)

In [36]:
# Find the standard deviation of the latest array
np.std(a4)

np.float64(2.6948510575210314)

In [37]:
# Find the variance of the latest array
np.var(a4)

np.float64(7.262222222222222)

In [38]:
# Reshape the latest array to (3, 5, 1)
a4.reshape(3, 5, 1)

array([[[9],
        [1],
        [9],
        [3],
        [7]],

       [[6],
        [8],
        [7],
        [4],
        [1]],

       [[4],
        [7],
        [9],
        [8],
        [8]]], dtype=int32)

In [39]:
# Transpose the latest array
a4.T

array([[9, 6, 4],
       [1, 8, 7],
       [9, 7, 9],
       [3, 4, 8],
       [7, 1, 8]], dtype=int32)

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

In [41]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1, mat2)

array([[16, 40],
       [14, 70],
       [14, 71]], dtype=int32)

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [44]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3.T, mat4)

array([[ 90,  86, 131],
       [ 56,  52,  98],
       [ 76,  62, 126]], dtype=int32)

In [45]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))

In [46]:
# Compare the two arrays with '>'
mat5 > mat6

array([[ True,  True],
       [ True,  True],
       [ True, False],
       [False, False]])

In [48]:
# Compare the two arrays with '>='
mat5 >= mat6

array([[ True,  True],
       [ True,  True],
       [ True, False],
       [ True, False]])

In [49]:
# Find which elements of the first array are greater than 7
mat5 > 7

array([[False, False],
       [ True,  True],
       [ True, False],
       [False, False]])

In [50]:
# Which parts of each array are equal? (try using '==')
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [51]:
# Sort one of the arrays you just created in ascending order
np.sort(mat5)

array([[6, 6],
       [8, 9],
       [2, 9],
       [0, 6]], dtype=int32)

In [52]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat6)

array([[0, 1],
       [0, 1],
       [1, 0],
       [1, 0]])

In [53]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat5)

np.int64(3)

In [54]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat6)

np.int64(7)

In [55]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat6, axis=1)

array([0, 1, 0, 0])

In [56]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(mat6, axis=0)

array([0, 3])

In [57]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.50144833,  1.15818665,  0.25711687,  0.3145129 ,  1.37186213],
       [ 0.17555329, -0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794, -0.39551645]])

In [59]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])